// Generated by scripts/generate_report_document_types.py. Do not edit by hand.

export interface ChartPoint {
  visit_date: string
  value: number
}

export interface EvidenceReference {
  evidence_bundle_id: string
  evidence_snapshot_sha256: string
}

export interface IndicatorLabel {
  code: string
  label: string
  allowed_units: (string)[]
  context_requirements: (string)[]
}

export interface InputAudit {
  task: string
  fields: (InputFieldAudit)[]
  frame_sha256: string | null
  numeric_imputation: string | null
  categorical_imputation: string | null
  model_invoked: boolean
  reason_code: string | null
}

export interface InputFieldAudit {
  name: string
  state: "present" | "allowed_missing" | "required_missing" | "invalid"
}

export interface ModelRunAudit {
  task: string
  target_label: string
  horizon_kind: "days" | "next_visit"
  horizon_days: number | null
  runtime: ModelRuntimeStatus
  input_audit: InputAudit
  training: TrainingDisclosure
  score_threshold: number | null
  risk_band_rule_version: string | null
}

export interface ModelRuntimeStatus {
  artifact_type: "outcome" | "stage" | "trend"
  task: string | null
  status: "available" | "missing" | "incompatible" | "disabled"
  reason_code: string
  lifecycle_status: "candidate" | "reviewed" | "enabled" | null
  model_id: string | null
  model_name: string | null
  model_version: string | null
  artifact_sha256: string | null
  target: string | null
  horizon_days: number | null
  feature_version: string | null
  score_semantics: string | null
  calibration_status: string | null
}

export interface ObservedChart {
  indicator: string
  label: string
  unit: string
  points: (ChartPoint)[]
}

export interface PinnedEvidenceToken {
  standard: PinnedStandard
  dataset_release_id: string | null
  data_content_sha256: string | null
  eligibility_config_hash: string
  similarity_config_hash: string
  logical_dataset: string | null
  reference_status: "reference_query_failed" | "reference_index_stale" | null
}

export interface PinnedStandard {
  standard_id: number
  version_id: number
  document_id: number
  document_sha256: string
  version_sha256: string
}

export interface QualityIssue {
  code: string
  severity: "blocking" | "warning" | "info"
  source: "input" | "model" | "standard" | "reference" | "observation"
  task: string | null
  visit_index: number | null
  indicator: string | null
  field: string | null
  message: string
  impact: string
  action: string
}

export interface ReportGenerationContext {
  schema_version: "report_generation_context.v1"
  disease_code: "fatty_liver" | "ad"
  release_set_id: string
  release_set_sha256: string
  data_release_id: string
  dataset_manifest_sha256: string
  split_sha256: string
  indicator_catalog_sha256: string
  indicator_labels: (IndicatorLabel)[]
  minimum_visits: number
  minimum_signal_observations: number
  standard_rules_sha256: string
  evidence_token: PinnedEvidenceToken
  template_version: "operator_report.zh-CN.v1"
}

export interface ReportIdentity {
  report_id: number
  batch_id: string
  anonymous_case_code: string | null
  disease_code: "fatty_liver" | "ad"
  disease_name: string
  age: number
  sex: "male" | "female"
  baseline_stage: string
  baseline_stage_label: string
  created_at: string
  anchor_date: string
  horizon_days: number
  prediction_end_date: string
}

export interface ReportSection {
  number: number
  title: string
  paragraphs: (string)[]
  tables: (ReportTable)[]
}

export interface ReportSummary {
  observation_status: "available" | "limited"
  model_input_status: "satisfied" | "partial" | "unavailable"
  selected_model_count: number
  invoked_model_count: number
  available_model_count: number
  signal_count: number
  evidence_status: "complete" | "partial"
  limitations: (string)[]
}

export interface ReportTable {
  title: string
  headers: (string)[]
  rows: ((string)[])[]
}

export interface TrainingDisclosure {
  synthetic_in_formal_metrics: boolean | null
  clinical_validity_claim: boolean | null
  production_enabled: boolean | null
  training_file_sha256: string | null
  composition_note: string
}

export interface ReportDocumentV1 {
  schema_version: "report_document.v1"
  template_version: "operator_report.zh-CN.v1"
  identity: ReportIdentity
  generation_context: ReportGenerationContext
  summary: ReportSummary
  data_quality: (QualityIssue)[]
  model_runs: (ModelRunAudit)[]
  evidence: EvidenceReference
  review_items: (QualityIssue)[]
  charts: (ObservedChart)[]
  sections: (ReportSection)[]
}

export interface NumericAlgorithmIdentity {
  model_id: "last_value"
  algorithm_version: "synthetic_numeric.last_value.v1"
  input_schema_version: "synthetic_numeric_input.v1"
  implementation_sha256: string
  parameters_sha256: string
  clinical_validity_claim: false
  production_enabled: false
}

export interface NumericObservation {
  observation_id: string
  indicator: "mmse" | "alt"
  measured_on: string
  known_on: string
  value: number
  unit: string
  method: string
}

export interface NumericPacketSource {
  source_kind: "synthetic"
  is_synthetic: true
  generator_version: "synthetic-prediction.v1"
  run_id: string
}

export interface NumericPredictionInput {
  sample_id: string
  subject_id: string
  dependency_group_id: string
  task_id: string
  horizon_months: 6 | 12
  anchor_date: string
  anchor_observation_id: string | null
  input_observations: (NumericObservation)[]
  input_status: "available" | "unavailable"
  input_reason: "anchor_unavailable" | "population_not_confirmed" | "population_not_known_at_anchor" | "conflicting_history" | null
  history_coverage: "complete" | "unknown"
  history_state: "confirmed_none" | "observed" | "unknown"
  source: NumericPacketSource
}

export interface NumericSourceIdentity {
  source_kind: "synthetic"
  is_synthetic: true
  generator_version: "synthetic-prediction.v1"
  run_id: string
  manifest_sha256: string
  input_file_sha256: string
}

export interface NumericTaskPrediction {
  task_id: string
  indicator: "mmse" | "alt"
  unit: "分" | "U/L"
  horizon_months: 6 | 12
  target_date: string
  status: "available" | "unavailable"
  value: number | null
  reason: "anchor_unavailable" | "population_not_confirmed" | "population_not_known_at_anchor" | "conflicting_history" | null
}

export interface SyntheticGenerationContext {
  schema_version: "synthetic_numeric_generation_context.v1"
  disease_code: "ad" | "fatty_liver"
  numeric_input_sha256: string
  engineering_source_sha256: string
  algorithm: NumericAlgorithmIdentity
  template_version: "synthetic_numeric_report.zh-CN.v1"
}

export interface SyntheticNumericInput {
  schema_version: "synthetic_numeric_input.v1"
  disease_code: "ad" | "fatty_liver"
  subject_id: string
  dependency_group_id: string
  anchor_date: string
  source: NumericSourceIdentity
  packets: (NumericPredictionInput)[]
}

export interface SyntheticNumericPrediction {
  schema_version: "synthetic_numeric_prediction.v1"
  disease_code: "ad" | "fatty_liver"
  subject_id: string
  dependency_group_id: string
  anchor_date: string
  source: NumericSourceIdentity
  input_sha256: string
  algorithm: NumericAlgorithmIdentity
  predictions: (NumericTaskPrediction)[]
}

export interface SyntheticReportIdentity {
  report_id: number
  batch_id: string
  anonymous_case_code: string
  disease_code: "ad" | "fatty_liver"
  disease_name: string
  age: number
  sex: "male" | "female"
  baseline_stage: string
  created_at: string
  anchor_date: string
}

export interface SyntheticNumericReportDocumentV1 {
  schema_version: "synthetic_numeric_report_document.v1"
  template_version: "synthetic_numeric_report.zh-CN.v1"
  identity: SyntheticReportIdentity
  generation_context: SyntheticGenerationContext
  numeric_input: SyntheticNumericInput
  prediction: SyntheticNumericPrediction
}

export interface NumericAlgorithm {
  model_id: "last_value"
  algorithm_version: "numeric.last_value.v1"
  input_schema_version: "numeric_input.v1"
  implementation_sha256: string
  parameters_sha256: string
  clinical_validity_claim: false
  production_enabled: false
}

export interface NumericGenerationContext {
  schema_version: "numeric_generation_context.v1"
  disease_code: "ad" | "fatty_liver"
  numeric_input_sha256: string
  source_binding_sha256: string
  algorithm: NumericAlgorithm
  template_version: "numeric_report.zh-CN.v1"
}

export interface NumericInput {
  schema_version: "numeric_input.v1"
  disease_code: "ad" | "fatty_liver"
  subject_id: string
  dependency_group_id: string
  anchor_date: string
  source: PredictionSource
  packets: (NumericInputPacket)[]
}

export interface NumericInputPacket {
  sample_id: string
  subject_id: string
  dependency_group_id: string
  task_id: string
  horizon_months: 6 | 12
  anchor_date: string
  anchor_observation_id: string | null
  input_observations: (NumericObservation)[]
  input_status: "available" | "unavailable"
  input_reason: "anchor_unavailable" | "population_not_confirmed" | "population_not_known_at_anchor" | "conflicting_history" | null
  history_coverage: "complete" | "unknown"
  history_state: "confirmed_none" | "observed" | "unknown"
  source: PredictionPacketSource
}

export interface NumericPrediction {
  schema_version: "numeric_prediction.v1"
  disease_code: "ad" | "fatty_liver"
  subject_id: string
  dependency_group_id: string
  anchor_date: string
  source: PredictionSource
  input_sha256: string
  algorithm: NumericAlgorithm
  predictions: (NumericTaskPrediction)[]
}

export interface NumericReportIdentity {
  report_id: number
  batch_id: string
  anonymous_case_code: string
  disease_code: "ad" | "fatty_liver"
  disease_name: string
  age: number
  sex: "male" | "female"
  baseline_stage: string
  created_at: string
  anchor_date: string
}

export interface PredictionPacketSource {
  source_kind: "synthetic" | "real"
  is_synthetic: boolean
  dataset_id: string
  dataset_version: string
  run_id: string
  generator_version: string | null
}

export interface PredictionSource {
  source_kind: "synthetic" | "real"
  is_synthetic: boolean
  dataset_id: string
  dataset_version: string
  run_id: string
  generator_version: string | null
  manifest_sha256: string
  input_file_sha256: string
}

export interface NumericReportDocumentV1 {
  schema_version: "numeric_report_document.v1"
  template_version: "numeric_report.zh-CN.v1"
  identity: NumericReportIdentity
  generation_context: NumericGenerationContext
  numeric_input: NumericInput
  prediction: NumericPrediction
}

export type JsonValue = unknown

export interface NumericBundleSource {
  cases: NumericBundleSourceItem
  calculation: NumericBundleSourceItem
}

export interface NumericBundleSourceItem {
  run_id: string
  data_content_sha256: string
}

export interface NumericGenerationContextV2 {
  schema_version: "numeric_generation_context.v2"
  disease_code: "ad" | "fatty_liver"
  numeric_input_sha256: string
  source_binding_sha256: string
  model_bundle: NumericModelBundle
  algorithm: TrainedNumericAlgorithm
  references: NumericReferenceContext
  llm_model: string
  prompt_text: string
  prompt_sha256: string
  retrieval_settings: NumericRetrievalSettings
  prompt_version: "numeric_narrative.prompt.v1"
  template_version: "numeric_report.zh-CN.v2"
}

export interface NumericModelBundle {
  schema_version: "numeric_model_bundle.v1"
  model_id: "ridge:main_anchor"
  algorithm_version: "numeric.ridge.main_anchor.v1"
  input_schema_version: "numeric_input.v1"
  implementation_sha256: string
  models: (NumericRidgeTask)[]
  source: NumericBundleSource
  challenge_subject_ids: (string)[]
  challenge_dependency_groups: (string)[]
  evaluation: { [key: string]: JsonValue }
  evaluation_sha256: string
  clinical_validity_claim: false
  production_enabled: false
}

export interface NumericNarrative {
  sections: (NumericNarrativeSection)[]
  limitations: (string)[]
  schema_version: "numeric_narrative.v1"
  status: "completed"
  model: string
  response_model: string | null
  prompt_version: "numeric_narrative.prompt.v1"
  prompt_sha256: string
  input_sha256: string
  prediction_sha256: string
  evidence_sha256: string
  output_sha256: string
  response_text: string
}

export interface NumericNarrativeSection {
  title: string
  text: string
  citation_ids: (number)[]
}

export interface NumericRagEvidence {
  schema_version: "numeric_rag_evidence.v1"
  input_sha256: string
  context_sha256: string
  status: "complete" | "partial" | "empty"
  vector_status: "complete" | "failed" | "not_run"
  fulltext_status: "complete" | "failed" | "not_run"
  embedding_model: string
  collection_name: string
  rrf_k: number
  query: string
  items: (NumericRetrievedEvidence)[]
}

export interface NumericReferenceChunk {
  chunk_id: number
  document_id: number
  document_version: number
  generation: number
  title: string
  content: string
  content_sha256: string
  department_id: null
  access_scope: "operator" | "both"
  disease_code: "ad" | "fatty_liver"
  subject_id: string
  dependency_group_id: string
  known_on: string
  pool: "development_pool"
  source: PredictionSource
}

export interface NumericReferenceContext {
  schema_version: "numeric_reference_context.v1"
  input_sha256: string
  disease_code: "ad" | "fatty_liver"
  anchor_date: string
  catalog_sha256: string
  candidates: (NumericReferenceChunk)[]
}

export interface NumericRetrievalSettings {
  embedding_model: string
  collection_name: string
  rrf_k: number
  vector_top_k: number
  fulltext_top_k: number
  final_top_k: number
}

export interface NumericRetrievedEvidence {
  chunk_id: number
  document_id: number
  document_version: number
  generation: number
  title: string
  content: string
  content_sha256: string
  department_id: null
  access_scope: "operator" | "both"
  disease_code: "ad" | "fatty_liver"
  subject_id: string
  dependency_group_id: string
  known_on: string
  pool: "development_pool"
  source: PredictionSource
  score: number
  vector_score: number | null
  vector_rank: number | null
  fulltext_score: number | null
  fulltext_rank: number | null
}

export interface NumericRidgeTask {
  task_id: "ad.mmse.6m" | "ad.mmse.12m" | "fatty_liver.alt.6m" | "fatty_liver.alt.12m"
  indicator: "mmse" | "alt"
  unit: "分" | "U/L"
  horizon_months: 6 | 12
  feature_names: ("anchor_value")[]
  mean: (number)[]
  std: (number)[]
  scale: (number)[]
  coef: (number)[]
  intercept: number
  training_sample_ids: (string)[]
  training_subject_ids: (string)[]
  training_dependency_groups: (string)[]
  training_identity_sha256: string
  training_data_sha256: string
  parameters_sha256: string
}

export interface TrainedNumericAlgorithm {
  model_id: "ridge:main_anchor"
  algorithm_version: "numeric.ridge.main_anchor.v1"
  input_schema_version: "numeric_input.v1"
  implementation_sha256: string
  parameters_sha256: string
  clinical_validity_claim: false
  production_enabled: false
  bundle_sha256: string
}

export interface TrainedNumericPrediction {
  schema_version: "numeric_prediction.v2"
  disease_code: "ad" | "fatty_liver"
  subject_id: string
  dependency_group_id: string
  anchor_date: string
  source: PredictionSource
  input_sha256: string
  algorithm: TrainedNumericAlgorithm
  predictions: (NumericTaskPrediction)[]
  baseline_predictions: (NumericTaskPrediction)[]
}

export interface NumericReportDocumentV2 {
  schema_version: "numeric_report_document.v2"
  template_version: "numeric_report.zh-CN.v2"
  identity: NumericReportIdentity
  generation_context: NumericGenerationContextV2
  numeric_input: NumericInput
  prediction: TrainedNumericPrediction
  evidence: NumericRagEvidence
  narrative: NumericNarrative
}

export interface AggregateCounts {
  N_label_valid: AggregateValue
  N_pair_valid: AggregateValue
}

export interface AggregateMetric {
  mean: number
  min: number
  max: number
  n_valid: 3
  n_invalid: 0
  missing_seeds: (20260914 | 20260915 | 20260916)[]
}

export interface AggregateMetrics {
  bias: AggregateMetric
  mae: AggregateMetric
  mae_gain_reference_minus_candidate: AggregateMetric
  reference_mae: AggregateMetric
  rmse: AggregateMetric
}

export interface AggregateValue {
  mean: number
  min: number
  max: number
  n_valid: 3
  n_invalid: 0
}

export interface EmptyEvidenceIntervals {
}

export interface EvidenceCounts {
  N_patient: number
  N_anchor_eligible: number
  N_anchor_ineligible: number
  N_anchor_pending: number
  N_history_eligible: number
  N_history_unavailable: number
  N_branch_eligible: number
  N_original_eligible: number
  N_common_complete: number
  N_common_excluded: number
  N_common_excluded_due_to_output: number
  N_label_valid: number
  N_label_absent: number
  N_label_pending: number
  N_label_not_applicable: number
  N_pair_valid: number
  N_dependency_groups: number
  N_candidate_out_of_range: number
  N_reference_out_of_range: number
  N_all_candidate_out_of_range: number
  N_all_reference_out_of_range: number
  N_pred_valid: number
  N_pred_abstain: number
  N_pred_error: number
  N_reference_valid: number
  N_reference_abstain: number
  N_reference_error: number
  N_original_pred_valid: number
  N_original_pred_abstain: number
  N_original_pred_error: number
  N_original_reference_valid: number
  N_original_reference_abstain: number
  N_original_reference_error: number
  N_all_pred_valid: number
  N_all_pred_abstain: number
  N_all_pred_error: number
  N_all_reference_valid: number
  N_all_reference_abstain: number
  N_all_reference_error: number
}

export interface EvidenceCoverage {
  label_support: EvidenceRatio
  paired: EvidenceRatio
  end_to_end: EvidenceRatio
}

export interface EvidenceInterval {
  status: "estimated" | "unavailable"
  reason: string | null
  lower: number | null
  upper: number | null
  width: number | null
  attempted: number
  valid: number
  failed: number
}

export interface EvidenceIntervals {
  bias: EvidenceInterval
  mae: EvidenceInterval
  mae_gain_reference_minus_candidate: EvidenceInterval
  reference_mae: EvidenceInterval
  rmse: EvidenceInterval
}

export interface EvidenceJointStates {
  both_valid: number
  candidate_unavailable: number
  reference_unavailable: number
  both_unavailable: number
}

export interface EvidenceRatio {
  value: number | null
  numerator: number
  denominator: number
  reason: "zero_denominator" | null
}

export interface EvidenceStatistics {
  mae: number | null
  rmse: number | null
  bias: number | null
  reference_mae: number | null
  mae_gain_reference_minus_candidate: number | null
  alpha: number | null
  beta: number | null
  n_patients: number
  n_groups: number
  unavailable: (string)[]
}

export interface MixedNumericAlgorithm {
  model_id: "mixed_history"
  algorithm_version: "numeric.mixed_history.v1"
  input_schema_version: "numeric_input.v1"
  implementation_sha256: string
  parameters_sha256: string
  clinical_validity_claim: false
  production_enabled: false
  bundle_sha256: string
}

export interface NumericGenerationContextV3 {
  schema_version: "numeric_generation_context.v3"
  disease_code: "ad" | "fatty_liver"
  numeric_input: NumericInput
  numeric_input_sha256: string
  source_binding_sha256: string
  model_bundle: NumericHistoryBundle
  algorithm: MixedNumericAlgorithm
  task_algorithms: { [key: string]: NumericTaskAlgorithm }
  references: NumericReferenceContext
  llm_model: string
  prompt_text: string
  prompt_sha256: string
  retrieval_settings: NumericRetrievalSettings
  prompt_version: "numeric_narrative.prompt.v2"
  template_version: "numeric_report.zh-CN.v3"
}

export interface NumericHistoryAggregateEvidence {
  evaluation_role: "training" | "internal_validation" | "challenge"
  task_id: "ad.mmse.12m"
  family: "random_forest"
  comparison_name: "value_history_vs_last_value" | "value_history_vs_anchor_history"
  scope: "original" | "common_complete"
  candidate_model_id: "random_forest:history_v1:value_history"
  reference_model_id: "last_value" | "random_forest:history_v1:anchor_history"
  gain_name: "mae_gain_reference_minus_candidate"
  unit: "分"
  expected_seeds: [20260914, 20260915, 20260916]
  seeds: [20260914, 20260915, 20260916]
  missing_seeds: (20260914 | 20260915 | 20260916)[]
  n_present_seeds: 3
  effective_seeds: [20260914, 20260915, 20260916]
  n_effective_seeds: 3
  complete: true
  incomplete: false
  gain_direction: "positive" | "negative" | "zero" | "mixed"
  metrics: AggregateMetrics
  counts: AggregateCounts
  source_kind: "synthetic"
  clinical_validity_claim: false
  clinical_status: "not_assessable"
}

export interface NumericHistoryBundle {
  schema_version: "numeric_model_bundle.v2"
  selection_version: "numeric_history_selection.v1"
  input_schema_version: "numeric_input.v1"
  implementation_sha256: string
  clinical_validity_claim: false
  production_enabled: boolean
  legacy_bundle: NumericModelBundle
  legacy_bundle_sha256: string
  history_model: NumericHistoryRfModel
  task_assignments: (NumericHistoryTaskAssignment)[]
  history_evidence: NumericHistoryEvidence
}

export interface NumericHistoryComparisonEvidence {
  seed: 20260914
  comparison_id: string
  task_id: "ad.mmse.12m"
  pool: "development_pool" | "challenge_pool"
  evaluation_role: "training" | "internal_validation" | "challenge"
  family: "random_forest"
  comparison_name: "value_history_vs_last_value" | "value_history_vs_anchor_history"
  scope: "original" | "common_complete"
  candidate_model_id: "random_forest:history_v1:value_history"
  reference_model_id: "last_value" | "random_forest:history_v1:anchor_history"
  gain_name: "mae_gain_reference_minus_candidate"
  unit: "分"
  counts: EvidenceCounts
  joint_states: EvidenceJointStates
  coverage: EvidenceCoverage
  complete_output: true
  statistics: EvidenceStatistics
  intervals: EvidenceIntervals | EmptyEvidenceIntervals
  common_scope_limited: false
  bootstrap_plan_id: string | null
  uncertainty_scope: "descriptive_only" | "synthetic_fixed_challenge_group_bootstrap"
  clinical_status: "not_assessable"
}

export interface NumericHistoryEvidence {
  schema_version: "numeric_history_evidence.v1"
  source_kind: "synthetic"
  clinical_status: "not_assessable"
  clinical_validity_claim: false
  run_id: string
  manifest_sha256: string
  data_content_sha256: string
  protocol_identity_sha256: string
  selection: NumericHistorySelection
  source_seed: 20260914
  model_id: "random_forest:history_v1:value_history"
  training_identity_sha256: string
  parameters_sha256: string
  challenge_subject_ids: (string)[]
  challenge_dependency_groups: (string)[]
  comparisons: (NumericHistoryComparisonEvidence)[]
  aggregates: (NumericHistoryAggregateEvidence)[]
}

export interface NumericHistoryRfModel {
  task_id: "ad.mmse.12m"
  model_id: "random_forest:history_v1:value_history"
  feature_names: ("anchor_value" | "prior_value" | "slope_per_day")[]
  mean: (number)[]
  std: (number)[]
  scale: (number)[]
  parameters: RfParameters
  trees: (RfTree)[]
  source_seed: number
  training_sample_ids: (string)[]
  training_subject_ids: (string)[]
  training_dependency_groups: (string)[]
  training_identity_sha256: string
  training_data_sha256: string
  training_target_sha256: string
  parameters_sha256: string
}

export interface NumericHistorySelection {
  schema_version: "numeric_history_selection.v1"
  seed: 20260914
  task_id: "ad.mmse.12m"
  model_id: "random_forest:history_v1:value_history"
}

export interface NumericHistoryTaskAssignment {
  task_id: "ad.mmse.6m" | "ad.mmse.12m" | "fatty_liver.alt.6m" | "fatty_liver.alt.12m"
  provider: "legacy_ridge" | "history_rf"
}

export interface NumericNarrativeSectionV2 {
  title: "结果阅读说明" | "参考证据说明"
  text: string
  citation_ids: (number)[]
}

export interface NumericNarrativeV2 {
  sections: (NumericNarrativeSectionV2)[]
  limitations: (string)[]
  schema_version: "numeric_narrative.v2"
  status: "completed"
  model: string
  response_model: string | null
  prompt_version: "numeric_narrative.prompt.v2"
  prompt_sha256: string
  input_sha256: string
  prediction_sha256: string
  evidence_sha256: string
  output_sha256: string
  response_text: string
}

export interface NumericPredictionV3 {
  schema_version: "numeric_prediction.v3"
  disease_code: "ad" | "fatty_liver"
  subject_id: string
  dependency_group_id: string
  anchor_date: string
  source: PredictionSource
  input_sha256: string
  algorithm: MixedNumericAlgorithm
  predictions: (NumericTaskPredictionV3)[]
  baseline_predictions: (NumericTaskPredictionV3)[]
}

export interface NumericTaskAlgorithm {
  model_id: "ridge:main_anchor" | "random_forest:history_v1:value_history" | "last_value"
  algorithm_version: "numeric.ridge.main_anchor.v1" | "numeric.random_forest.history_v1.value_history.v1" | "numeric.last_value.v1"
  feature_version: "main_anchor" | "history_v1:value_history"
  eligibility_version: "numeric.anchor.v1" | "numeric.history.H.v1"
  feature_names: ("anchor_value" | "prior_value" | "slope_per_day")[]
  parameters_sha256: string
}

export interface NumericTaskPredictionV3 {
  task_id: "ad.mmse.6m" | "ad.mmse.12m" | "fatty_liver.alt.6m" | "fatty_liver.alt.12m"
  indicator: "mmse" | "alt"
  unit: "分" | "U/L"
  horizon_months: 6 | 12
  target_date: string
  algorithm: NumericTaskAlgorithm
  status: "available" | "abstain" | "error"
  value: number | null
  reason: "anchor_unavailable" | "population_not_confirmed" | "population_not_known_at_anchor" | "conflicting_history" | "history_coverage_incomplete" | "history_not_observed" | "comparable_history_required" | "history_calculation_error" | "standardization_error" | "prediction_calculation_error" | "nonfinite_prediction" | "prediction_out_of_bounds" | null
  raw_prediction: number | null
}

export interface RfBranch {
  kind: "branch"
  feature_index: number
  threshold: number
  left: number
  right: number
}

export interface RfLeaf {
  kind: "leaf"
  value: number
}

export interface RfParameters {
  n_estimators: number
  criterion: "squared_error"
  max_depth: number
  min_samples_split: number
  min_samples_leaf: number
  min_weight_fraction_leaf: number
  max_features: number
  max_leaf_nodes: null
  min_impurity_decrease: number
  bootstrap: boolean
  oob_score: boolean
  n_jobs: number
  random_state: number
  verbose: number
  warm_start: boolean
  ccp_alpha: number
  max_samples: null
  monotonic_cst: null
}

export interface RfTree {
  nodes: (RfBranch | RfLeaf)[]
}

export interface NumericReportDocumentV3 {
  schema_version: "numeric_report_document.v3"
  template_version: "numeric_report.zh-CN.v3"
  identity: NumericReportIdentity
  generation_context: NumericGenerationContextV3
  numeric_input: NumericInput
  prediction: NumericPredictionV3
  evidence: NumericRagEvidence
  narrative: NumericNarrativeV2
}

export type AnyReportDocument = ReportDocumentV1 | SyntheticNumericReportDocumentV1 | NumericReportDocumentV1 | NumericReportDocumentV2 | NumericReportDocumentV3
