// Generated by scripts/generate_report_document_types.py. Do not edit by hand.

export interface ChartPoint {
  visit_date: string
  value: number
}

export interface EvidenceReference {
  evidence_bundle_id: string
  evidence_snapshot_sha256: string
}

export interface IndicatorLabel {
  code: string
  label: string
  allowed_units: (string)[]
  context_requirements: (string)[]
}

export interface InputAudit {
  task: string
  fields: (InputFieldAudit)[]
  frame_sha256: string | null
  numeric_imputation: string | null
  categorical_imputation: string | null
  model_invoked: boolean
  reason_code: string | null
}

export interface InputFieldAudit {
  name: string
  state: "present" | "allowed_missing" | "required_missing" | "invalid"
}

export interface ModelRunAudit {
  task: string
  target_label: string
  horizon_kind: "days" | "next_visit"
  horizon_days: number | null
  runtime: ModelRuntimeStatus
  input_audit: InputAudit
  training: TrainingDisclosure
  score_threshold: number | null
  risk_band_rule_version: string | null
}

export interface ModelRuntimeStatus {
  artifact_type: "outcome" | "stage" | "trend"
  task: string | null
  status: "available" | "missing" | "incompatible" | "disabled"
  reason_code: string
  lifecycle_status: "candidate" | "reviewed" | "enabled" | null
  model_id: string | null
  model_name: string | null
  model_version: string | null
  artifact_sha256: string | null
  target: string | null
  horizon_days: number | null
  feature_version: string | null
  score_semantics: string | null
  calibration_status: string | null
}

export interface ObservedChart {
  indicator: string
  label: string
  unit: string
  points: (ChartPoint)[]
}

export interface PinnedEvidenceToken {
  standard: PinnedStandard
  dataset_release_id: string | null
  data_content_sha256: string | null
  eligibility_config_hash: string
  similarity_config_hash: string
  logical_dataset: string | null
  reference_status: "reference_query_failed" | "reference_index_stale" | null
}

export interface PinnedStandard {
  standard_id: number
  version_id: number
  document_id: number
  document_sha256: string
  version_sha256: string
}

export interface QualityIssue {
  code: string
  severity: "blocking" | "warning" | "info"
  source: "input" | "model" | "standard" | "reference" | "observation"
  task: string | null
  visit_index: number | null
  indicator: string | null
  field: string | null
  message: string
  impact: string
  action: string
}

export interface ReportGenerationContext {
  schema_version: "report_generation_context.v1"
  disease_code: "fatty_liver" | "ad"
  release_set_id: string
  release_set_sha256: string
  data_release_id: string
  dataset_manifest_sha256: string
  split_sha256: string
  indicator_catalog_sha256: string
  indicator_labels: (IndicatorLabel)[]
  minimum_visits: number
  minimum_signal_observations: number
  standard_rules_sha256: string
  evidence_token: PinnedEvidenceToken
  template_version: "operator_report.zh-CN.v1"
}

export interface ReportIdentity {
  report_id: number
  batch_id: string
  anonymous_case_code: string | null
  disease_code: "fatty_liver" | "ad"
  disease_name: string
  age: number
  sex: "male" | "female"
  baseline_stage: string
  baseline_stage_label: string
  created_at: string
  anchor_date: string
  horizon_days: number
  prediction_end_date: string
}

export interface ReportSection {
  number: number
  title: string
  paragraphs: (string)[]
  tables: (ReportTable)[]
}

export interface ReportSummary {
  observation_status: "available" | "limited"
  model_input_status: "satisfied" | "partial" | "unavailable"
  selected_model_count: number
  invoked_model_count: number
  available_model_count: number
  signal_count: number
  evidence_status: "complete" | "partial"
  limitations: (string)[]
}

export interface ReportTable {
  title: string
  headers: (string)[]
  rows: ((string)[])[]
}

export interface TrainingDisclosure {
  synthetic_in_formal_metrics: boolean | null
  clinical_validity_claim: boolean | null
  production_enabled: boolean | null
  training_file_sha256: string | null
  composition_note: string
}

export interface ReportDocumentV1 {
  schema_version: "report_document.v1"
  template_version: "operator_report.zh-CN.v1"
  identity: ReportIdentity
  generation_context: ReportGenerationContext
  summary: ReportSummary
  data_quality: (QualityIssue)[]
  model_runs: (ModelRunAudit)[]
  evidence: EvidenceReference
  review_items: (QualityIssue)[]
  charts: (ObservedChart)[]
  sections: (ReportSection)[]
}
