"""Generate the JSON DTO from the authoritative Pydantic document schema."""

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.schemas.report_document import ReportDocument


def ts(node):
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return json.dumps(node["const"], ensure_ascii=False)
    if "enum" in node:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts(v) for v in node["anyOf"])
    kind = node.get("type")
    if kind == "array":
        return "(" + ts(node["items"]) + ")[]"
    if kind == "object":
        return "Record<string, unknown>"
    return {
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
        "string": "string",
    }.get(kind, "unknown")


def generate():
    schema = ReportDocument.model_json_schema()
    definitions = {**schema.pop("$defs"), "ReportDocumentV1": schema}
    output = [
        "// Generated by scripts/generate_report_document_types.py. Do not edit by hand.",
        "",
    ]
    for name, node in definitions.items():
        output.append("export interface " + name + " {")
        for key, value in node["properties"].items():
            output.append("  " + key + ": " + ts(value))
        output.extend(["}", ""])
    return "\n".join(output)


if __name__ == "__main__":
    (ROOT / "frontend/src/types").mkdir(exist_ok=True)
    (ROOT / "frontend/src/types/report-document.ts").write_text(
        generate(), encoding="utf-8"
    )
