"""Generate the JSON DTO from the authoritative Pydantic document schema."""

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.schemas.report_document import ReportDocument, SyntheticNumericReportDocument
from app.schemas.numeric_report import NumericReportDocument
from app.schemas.numeric_report_v2 import NumericReportDocumentV2
from app.schemas.numeric_report_v3 import NumericReportDocumentV3


def ts(node):
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return json.dumps(node["const"], ensure_ascii=False)
    if "enum" in node:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts(v) for v in node["anyOf"])
    if "oneOf" in node:
        return " | ".join(ts(v) for v in node["oneOf"])
    kind = node.get("type")
    if kind == "array":
        if "prefixItems" in node:
            return "[" + ", ".join(ts(v) for v in node["prefixItems"]) + "]"
        return "(" + ts(node["items"]) + ")[]"
    if kind == "object":
        if isinstance(node.get("additionalProperties"), dict):
            return "{ [key: string]: " + ts(node["additionalProperties"]) + " }"
        return "Record<string, unknown>"
    return {
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
        "string": "string",
    }.get(kind, "unknown")


def generate():
    schema = ReportDocument.model_json_schema()
    definitions = {**schema.pop("$defs"), "ReportDocumentV1": schema}
    numeric_schema = SyntheticNumericReportDocument.model_json_schema()
    for name, definition in numeric_schema.pop("$defs").items():
        if name in definitions and definitions[name] != definition:
            raise ValueError("conflicting_report_type_definition")
        definitions[name] = definition
    definitions["SyntheticNumericReportDocumentV1"] = numeric_schema
    unified_schema = NumericReportDocument.model_json_schema()
    for name, definition in unified_schema.pop("$defs").items():
        if name in definitions and definitions[name] != definition:
            raise ValueError("conflicting_report_type_definition")
        definitions[name] = definition
    definitions["NumericReportDocumentV1"] = unified_schema
    trained_schema = NumericReportDocumentV2.model_json_schema()
    for name, definition in trained_schema.pop("$defs").items():
        if name in definitions and definitions[name] != definition:
            raise ValueError("conflicting_report_type_definition")
        definitions[name] = definition
    definitions["NumericReportDocumentV2"] = trained_schema
    history_schema = NumericReportDocumentV3.model_json_schema()
    for name, definition in history_schema.pop("$defs").items():
        if name in definitions and definitions[name] != definition:
            raise ValueError("conflicting_report_type_definition")
        definitions[name] = definition
    definitions["NumericReportDocumentV3"] = history_schema
    output = [
        "// Generated by scripts/generate_report_document_types.py. Do not edit by hand.",
        "",
    ]
    for name, node in definitions.items():
        if "properties" not in node:
            output.extend(["export type " + name + " = " + ts(node), ""])
            continue
        output.append("export interface " + name + " {")
        for key, value in node["properties"].items():
            output.append("  " + key + ": " + ts(value))
        output.extend(["}", ""])
    output.append("export type AnyReportDocument = ReportDocumentV1 | SyntheticNumericReportDocumentV1 | NumericReportDocumentV1 | NumericReportDocumentV2 | NumericReportDocumentV3")
    output.append("")
    return "\n".join(output)


if __name__ == "__main__":
    (ROOT / "frontend/src/types").mkdir(exist_ok=True)
    (ROOT / "frontend/src/types/report-document.ts").write_text(
        generate(), encoding="utf-8"
    )
